### ISSUE TITLE
Multiple collections combined gives new problems

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#110]
I've been experimenting with adding more descriptive metadata and found the following problem:
There are two different collections:
- https://iiif.socialhistory.org/iiif/presentation/collection/COLL00097.dig3229?pretty
- https://iiif.socialhistory.org/iiif/presentation/collection/COLL00097.dig3588?pretty

However, they are both connected together through a metadata only collection: https://iiif.socialhistory.org/iiif/presentation/collection/COLL00097?pretty

This results in the following problem:
1) I got access to the first collection COLL00097.dig3229 with token _jD5ak5HD7HhfR86aF6FR_ 
2) So, I open the viewer with a reference to that collection: https://iiif.socialhistory.org/archivalviewer/?manifest=https://iiif.socialhistory.org/iiif/presentation/collection/COLL00097.dig3229 
3) I am asked for a code, which I enter and I am granted access
4) However, the viewer also finds the other collection COLL00097.dig3588 by following the links in the manifest and starts complaining about another code for accessing the other collection. However I don't have a code and want to cancel, but the viewer won't let me. The viewer won't allow me to just browse the collection COLL00097.dig3229 for which I have access.

I think there are two problems:
1) The viewer asks for access to a folder/collection, which the user did not select in the viewer. Only when the user clicks on the folder for COLL00097.dig3588, it should have asked for a code, not before.
2) The viewer is to eager with gathering collections for building the tree. Maybe the tree building should attempt a more lazy approach?

**Comment by Sozialarchiv** [comment]
I will check that

**Comment by Sozialarchiv** [comment]
@kerim1 At the moment I have full access to both collections?

> The viewer is to eager with gathering collections for building the tree. Maybe the tree building should attempt a more lazy approach?

I think this should be possible.

**Comment by kerim1** [comment]
Yes, I had changed the access again for testing purposes. Now they are both closed again, with access to COLL00097.dig3229 with token _jD5ak5HD7HhfR86aF6FR_

**Comment by Sozialarchiv** [comment]
@kerim1 

I can not reach the manifest anymore:
https://iiif.socialhistory.org/iiif/presentation/collection/COLL00097.dig3229

502 Bad Gateway

Can you make it available again.

**Comment by kerim1** [comment]
The server was shut down, but I started it again. It should be available again.

**Comment by Sozialarchiv** [comment]
I can reproduce it. It will make it more lazy.

**Comment by Sozialarchiv** [comment]
@kerim1 

I think I solved the issue. But I can not verify it with you example because the token jD5ak5HD7HhfR86aF6FR is not working anymore.
