### ISSUE TITLE
Viewer not working in IE11

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#111]
The viewer is not working in Internet Explorer 11. It might require some react polyfills?
![iiif-archival-viewer-ie11](https://user-images.githubusercontent.com/1478435/49939169-552be380-fedc-11e8-8d4e-08752c2baeb2.png)

**Comment by Sozialarchiv** [comment]
Ok. I will try to solve it.

**Comment by Sozialarchiv** [comment]
Solution:
1. Set target to es5
2. Add a `URL` polyfill

**Comment by kerim1** [comment]
I think we should set the target to es5 in tsconfig.json. Typescript works great for this.

On the other hand, the build now fails as it expects _tsconfig.prod.json_ file. The suggested solution is to include the default template in this repository: https://github.com/wmonk/create-react-app-typescript/blob/master/template/tsconfig.prod.json
