### ISSUE TITLE
Language button layout problem

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/viewer#134]
The language button is a bit lower than the others.

Tested on: Chrome on Mac

@eericq

**Comment by eericq** [comment]
<img width="712" alt="screenshot-language" src="https://user-images.githubusercontent.com/36766952/61115010-ce4ee180-a491-11e9-8e48-6a9b4db4776f.png">

**Comment by Sozialarchiv** [comment]
I have a fix I will upload it to the demo on Monday.
