### ISSUE TITLE
Add themes support

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/viewer#138]

**Comment by Sozialarchiv** [comment]
Do we really need theme support? Mirador has black dark theme. But it is really useful?

Instead of adding a theme I can add more id attributes to the code, that would make it easier to change the style of the viewer with an individual css file.

@kerim1, @eericq What do you think?

**Comment by kerim1** [comment]
I don't think there is a real demand for it right now. I would suggest the second option of adding more class attributes to the code. In addition, I would start working on CSS custom properties (variables) to make it easier for others to change the styling: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by kerim1** [comment]
Yes
