### ISSUE TITLE
Metadata not shown anymore

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#139]
The metadata is not shown in the viewer anymore. See for example: https://iiif.socialhistory.org/archivalviewer/?manifest=https://iiif.socialhistory.org/iiif/presentation/collection/COLL00154.dig2275

**Comment by Sozialarchiv** [comment]
Sorry for the slow anwser.

> The metadata is not shown in the viewer anymore. 

I can see the metadata in you example: "Refer to this item"

**Comment by kerim1** [comment]
Yes, not sure why it didn't work at the time.
