### ISSUE TITLE
Less universalviewer

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/viewer#15]
- [x] Audio
 - [x] Video
 - [x] pdf
 - [x] image

**Comment by Sozialarchiv** [comment]
@kerim1 @eericq There are good news. I could add audio, video, pdf and image support to the viewer. UniversalViewer is not needed anymore. 

I have to work more on the design but the most difficult part of this issue is done.

**Comment by kerim1** [comment]
Looks great, although the ultimate goal for the IISH is to eventually move to the Universal Viewer completely, once it better supports collections tree navigation and has improved IIIF-3 support.

**Comment by Sozialarchiv** [comment]
As soon as IIF-3 is official released I will add it to the viewer. 

IMHO Universal Viewer has not the goal to give you a file storage look and feel. So I guess uv will not reach the user experiance (even with treeview) we are focused on.

**Comment by kerim1** [comment]
I don't completely agree with you. It is true that the Universal Viewer does not provide the UX we are looking for at the moment. That is why we have this viewer instead for now. But the Universal Viewer can do a lot already and it would be a waste to reinvent the wheel and try to do things ourselves, when the Universal Viewer already has support for those features built-in. 

Then of course, you can also discuss whether you really want to give a viewer (and also the user) the file storage look-and-feel. Seeing where the Universal Viewer (and IIIF-3) is headed, I don't think it will be long before we can provide born digital content with the Universal Viewer with a good UX.
