### ISSUE TITLE
Use relative URLs

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#16]
When the viewer can be found at a URL like `http://localhost/public/viewer`, the viewer won't start with the following error messages in the console:
- 404 Not Found: http://localhost/static/css/main.d237b13c.css
- 404 Not Found: http://localhost/static/js/main.a332cb28.js
- 404 Not Found: http://localhost/manifest.json
Instead, it should use relative URLs, which are resolved to:
- http://localhost/public/viewer/static/css/main.d237b13c.css
- http://localhost/public/viewer/static/js/main.a332cb28.js
- http://localhost/public/viewer/manifest.json

**Comment by Sozialarchiv** [comment]
I will check that.

**Comment by kerim1** [comment]
Can be fixed by adding `"homepage": "."` to `package.json`.

**Comment by kerim1** [comment]
Still not working. It should have been added to `package.json`as a property and not as a dependency. Fixed with commit https://github.com/archival-IIIF/viewer/commit/30f981911dfa56a96cf4b773f45d6f47e4f6d847

**Comment by kerim1** [comment]
Can you reapply the commit https://github.com/archival-IIIF/viewer/commit/30f981911dfa56a96cf4b773f45d6f47e4f6d847 again? The homepage property is gone again.

**Comment by kerim1** [comment]
Unfortunatly still not there yet... Instead the homepage dependency is back again. And we don't need that dependency.

**Comment by kerim1** [comment]
Reopening this issue as `"homepage": "."` is again missing from `package.json`.

**Comment by kerim1** [comment]
https://github.com/archival-IIIF/viewer/commit/a64d86b13b9355e2abe042867a221405c390a4d3
