### ISSUE TITLE
Rendering deep folder structures

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#18]
Deep folder structures are not rendered correctly in the tree:
![image](https://user-images.githubusercontent.com/1478435/42437086-3c7d47f8-835c-11e8-991b-65a64b10b91f.png)
For each new child directory, the node gets a css class with a number representing the depth. However, only the classes up to level 4 are defined. The rendering should be smarter, so we don't have to define css classes for every single level in the tree.

**Comment by Sozialarchiv** [comment]
I will check that
