### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#19]
When the tree is too long, you have to scroll down to see the rest of the tree. However, the app doesn't expect this:
![image](https://user-images.githubusercontent.com/1478435/42437570-ca5486b2-835d-11e8-9290-63a376154120.png)
This should be fixed in the design, but a better approach would be to make the tree column scrollable.

**Comment by Sozialarchiv** [comment]
I will check that.
