### ISSUE TITLE
App.css introduces global styles that prevent reuse

### ISSUE THREAD

**Issue by barmintor** [archival-IIIF/viewer#192]
App.css defines global styles for `html`, `body`, `h1`, `h3`, `*`, etc. If a site attempts to use the viewer within its layout, this prevents it.

Since App accepts a parameterized element ID, there is an implication that the embedding site must do some styling to support the viewer. The global styles currently defined in App.css should be either:
1. Documented styles recommended to be used by the layout, or
2. Defined against classes (`h3.aiiif-header` rather than `h3` for example, or `.aiiif-root` rather than `#root`)

**Comment by Sozialarchiv** [comment]
That is a good hint. I will create a patch.
