### ISSUE TITLE
Add dutch translation

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/viewer#4]
Depends on: #3

**Comment by Sozialarchiv** [comment]
https://github.com/archival-IIIF/server/issues/24

**Comment by Sozialarchiv** [comment]
@eericq 

The translation system is ready. If you want you can add a dutch translation here:
https://github.com/archival-IIIF/viewer/tree/master/src/translations

Just copy the english file to start.

**Comment by Sozialarchiv** [comment]
@eericq Ping

**Comment by eericq** [comment]
Dutch translation created.

Is it really complete? I see in the viewer details extra labels, like 'Original file type'.

**Comment by Sozialarchiv** [comment]
Thank you

> Is it really complete? I see in the viewer details extra labels, like 'Original file type'.

Yes.  'Original file type' ist part of the manifest file. It has to be translated in the server component:
See: https://github.com/archival-IIIF/server/issues/24
