### ISSUE TITLE
Add support for authentication

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/viewer#42]
* [x] IIIF single file authentification
* [ ] Metadata block

See also:
- https://iiif.io/api/auth/1.0/
- https://iiif.io/api/auth/1.0/implementation/

Resources may have one of the following services:
- [https://iiif.io/api/auth/1.0/#login-interaction-pattern](http://iiif.io/api/auth/1/login) (Indicates a login screen is available for authentication)
- [https://iiif.io/api/auth/1.0/#external-interaction-pattern](http://iiif.io/api/auth/1/external) (Indicates access may also happen baed on the IP address)

What should the viewer do:
- For images: obtain the info.json document. If you receive a 401, the user has to authenticate.
- For other content: Perform a HEAD request for the content. If you receive a 401, the user has to authenticate.

In case of authentication:
1) Try the access token server of the external service. (If there is an external service defined)
2) If failed, try to open the login screen in a new window (The id of the login service) and wait for the screen to close.
3) Then try the access token server of the login service.

The services include the labels to use to tell the user what is required of him/her and what has happened.

The image info.json document may redirect to another info.json document with another id. In this case the image is degraded and there is a maxWidth/maxHeight enforced on image requests. This new id should be used for the image requests.
The server takes care of creating an access cookie for content requests. For API requests the obtained access token should be added to the header of each request.

It is also possible for the manifest/collection to return a 401. In that case the viewer should just tell the user that access is restricted.

**Comment by Sozialarchiv** [comment]
* [x] IIIF single file authentification
* [ ] Metadata block
