### ISSUE TITLE
Add embed

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/viewer#8]

**Comment by Sozialarchiv** [comment]
@eericq, @kerim1 

1. What should be embedded? Always the hole viewer? Or just a file?
2. Do you think it make sense to embed the viewer? Isn't to large? Is a link not always the better sharing option?

**Comment by Sozialarchiv** [comment]
@eericq Ping

**Comment by Sozialarchiv** [comment]
@eericq Ping

**Comment by eericq** [comment]
In general it is nice to be able to embed it, but you are right Fabian. It is too bit to embed. that doesn't make sense. A link would be enough. So skip this requirement.

**Comment by Sozialarchiv** [comment]
@eericq Maybe we can solve it like youtube with a share dialog.

![image](https://user-images.githubusercontent.com/17063042/84156316-a3865800-aa69-11ea-91e1-39a90406c7d9.png)

It would contain sharing buttons for 
* the iiif manifest url, 
* embed code, 
* email 
* and some social media sharing possibility.

**Comment by eericq** [comment]
Yes, this would be a nice solution. For now, this is not urgent. Our digital born archives are recent acquisitions and by default closed. There are too many privacy issues to  solve before sharing them with the world. So I don't see the need for these options in this phase.
