### ISSUE TITLE
Implement more auth methods

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/viewer#94]
* [x] Login
* [x] Clickthorugh
* [x] Kiosk
* [x] External

**Comment by Sozialarchiv** [comment]
Auth examples:
https://iiifauth.digtest.co.uk/

Note: The wellcomelibrary (E.g. http://wellcomelibrary.org/iiif/b1818893x/manifest) are just working in uv v1! So this examples are not a reference!

**Comment by Sozialarchiv** [comment]
https://iiif.io/api/auth/1.0/#external-interaction-pattern

@eericq @kerim1

I added the external authentication to future plans because I think we don't need it for IP based authentication , because in the IP based mode the manifest files are no accessible anyway.

**Comment by kerim1** [comment]
We do need external authentication for IP based authentication. The point of the external authentication pattern is to inform the user why the content is not available for them if they are not authorized. We need the external authentication pattern to tell the user that he can only access the content in the reading room of the IISH.

**Comment by Sozialarchiv** [comment]
@kerim1 I add external auth support.
